name: Regression test

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - create_addresses
          - click_required


jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: create_addresses
        if: "github.event.inputs.deployment_target == 'create_addresses'"
        run: mvn clean test -Dtest=CreateAdresTest
      - name: click_required
        if: "github.event.inputs.deployment_target == 'click_required'"
        run: mvn clean test -Dtest=ClickRequest

      - name: History test
      - uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: allure_history

      - name: Allure Result
        uses: simple-elf/allure-report-action@v1.7
        if: always().
        with:
          gh_pages: allure_history
          allure_results: allure_results
          allure_history: allure_history

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3.
        if: always().
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure_history




