name: Allure Report CI

on:
  push:
    branches: [ "work" ]
  pull_request:
    branches: [ "work" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build with Maven
        run: mvn -B clean test


      - name: History test
      - uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: allure_history

      - name: Allure Result
        uses: simple-elf/allure-report-action@v1.7
        if: always().
        with:
          gh_pages: allure_history
          allure_results: allure_results
          allure_history: allure_history

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3.
        if: always().
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure_history




